### PR TITLE
Added Dark and Light Modes for the application

### LINKED ISSUE #71: [FEATURE] Adding Dark Mode for the app
### Description

I'd add a dark-mode for the application, along with a switch option in the settings, through which the users would be able to switch between the dark and the light mode in the application. 

### Screenshots

image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jaivsh**
## Description

I've added both the dark as well as the light modes for the application. This can be switched from the settings section with the help of a toggle button, as shown in the screenshot below. Apart from that, 
- I've changed the static colors used in the screens with the dynamic ones to support light and dark modes
- Changed other small color components of UIs to match with dark and light modes.

Fixed #71 

## Screenshots

```Dark Mode :```

Screenshot_20230801_114109
Screenshot_20230801_115555
Screenshot_20230801_115638

```Light Mode :```
Screenshot_20230801_115722
Screenshot_20230801_115710

### CODE REVIEW

**Comment by jaivsh** [comment]
@bhattabhi013 check this PR asap!

**Comment by jaivsh** [comment]
@bhattabhi013 resolved the pubspec.lock issue for this PR, please review

**Comment by bhattabhi013** [comment]
Please resolve conflicts

**Comment by jaivsh** [comment]
> Please resolve conflicts

@bhattabhi013 resolved it, please check now

**Review by bhattabhi013 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
